services:
  - type: web
    name: walery
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "walery.onrender.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
