# Generated by Django 5.2.6 on 2025-09-24 06:39

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Allowed: jpg, png, gif, webp. Max 5 MB.', null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), core.models.validate_file_size]),
        ),
    ]
