# Generated by Django 5.2.6 on 2025-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
