# Generated by Django 5.2.6 on 2025-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_visitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='ref_type',
            field=models.CharField(default='direct', max_length=50),
        ),
    ]
