# Generated by Django 5.2.6 on 2025-11-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_visitlog_ref_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='ip',
        ),
    ]
