from pathlib import Path
import sys
import environ
import dj_database_url
from datetime import timedelta

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- django-environ init ---
env = environ.Env(
    DJANGO_DEBUG=(bool, True),  # default: True
)
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env("DJANGO_SECRET_KEY", default="dev-insecure-change-me")
DEBUG = env("DJANGO_DEBUG")
SENTRY_DSN = env("SENTRY_DSN", default=None)
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.redis import RedisIntegration
    sentry_sdk.init(dsn=SENTRY_DSN, integrations=[RedisIntegration()], traces_sample_rate=1.0, send_default_pii=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=["http://localhost", "http://127.0.0.1"])
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=["http://localhost", "http://127.0.0.1"])

# Security & Session settings
if not DEBUG:
    # Enforce HTTPS and related security features
    SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for 1 year (recommended for production)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS

    # Secure Cookies
    SESSION_COOKIE_SECURE = True  # Ensures cookies are only sent over HTTPS
    CSRF_COOKIE_SECURE = True  # Ensures CSRF cookie is only sent over HTTPS

    # X-Frame-Options to prevent clickjacking
    X_FRAME_OPTIONS = 'DENY'

    # Content Security Policy (CSP) Headers
    SECURE_BROWSER_XSS_FILTER = True  # Enable XSS filter in browsers
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps
    'core',
    'gallery',
    'tonguetwister',
    'rugby',
    'bies',
    'docdiff',
    'analytics',

    # External
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'base.middleware.LoginStreakMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gallery.context_processors.categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE - production uses DATABASE_URL; fallback to local sqlite for dev
DATABASE_URL = env("DATABASE_URL", default=None)
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    # Local/dev fallback
    DATABASES = {
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}
    }
# --- Force SQLite for pytest or Django test runner ---
if any(arg in sys.argv for arg in ["test", "pytest"]):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "test_db.sqlite3",
        }
    }

# REST API configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'tonguetwister.throttling.CustomAnonThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/hour',
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # JSON
        'rest_framework.renderers.BrowsableAPIRenderer' # UI
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Swagger configuration
SPECTACULAR_SETTINGS = {
    "TITLE": "Lingwołamki API",
    "DESCRIPTION": "Endpointy dla różnych modeli lingwołamków",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {"persistAuthorization": True},
    "COMPONENT_SPLIT_REQUEST": True,
    "SECURITY_DEFINITIONS": {
        "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
        }
    },
}

REDIS_URL = env("REDIS_URL", default=None)
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient", "SSL_CERT_REQS": None},
        }
    }
else:
    # Local fallback (dev)
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}


SENTRY_DSN = env("SENTRY_DSN", default=None)
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.redis import RedisIntegration
    sentry_sdk.init(dsn=SENTRY_DSN, integrations=[RedisIntegration()], traces_sample_rate=1.0, send_default_pii=False)


# JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / 'core/static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- Supabase (S3-compatible) via django-storages ---
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
SUPABASE_PROJECT_REF = env("SUPABASE_PROJECT_REF")

AWS_S3_ENDPOINT_URL = f"https://{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/s3"

# Public URL for use in templates (Supabase public object URL)
MEDIA_URL = f"https://{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}/"

# Options
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default=None)
AWS_QUERYSTRING_AUTH = False
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "public, max-age=86400"}

STORAGES = {
    "default": {
        "BACKEND": "core.storages_backends.SupabasePublicStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Email backend settings (using SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
BREVO_API_KEY = env("BREVO_API_KEY", default="")
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="webmaster@localhost")
EMAIL_TIMEOUT = 10

# Logins
LOGIN_URL = "/admin69/login/"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "main"

# 1) Enforce SameSite on cookies to reduce CSRF risk
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

#  Start in report-only mode. After monitoring set SECURE_CSP_REPORT_ONLY = False to enforce.
SECURE_CSP_REPORT_ONLY = True
SECURE_CSP = {
    # directive: policy (use strings, include quotes where needed)
    "default-src": "'self'",
    "img-src": "'self' data: https:",
    "script-src": "'self'",
    "style-src": "'self' https://fonts.googleapis.com",
    "font-src": "'self' https://fonts.gstatic.com",
    "frame-ancestors": "'none'",
}

# Define a simple middleware factory here so it is importable as 'config.settings.csp_headers'
def csp_headers(get_response):
    """
    Simple middleware that injects a CSP header.
    It uses REPORT-ONLY mode while SECURE_CSP_REPORT_ONLY is True.
    """
    def middleware(request):
        response = get_response(request)
        # Build policy string like: "default-src 'self'; img-src 'self' data: https:; ..."
        csp_policy = "; ".join(f"{k} {v}" for k, v in SECURE_CSP.items())
        header_name = "Content-Security-Policy-Report-Only" if SECURE_CSP_REPORT_ONLY else "Content-Security-Policy"
        response[header_name] = csp_policy
        return response
    return middleware

# Insert our CSP middleware right after SecurityMiddleware if that middleware exists.
try:
    idx = MIDDLEWARE.index("django.middleware.security.SecurityMiddleware") + 1
    MIDDLEWARE.insert(idx, "config.settings.csp_headers")
except ValueError:
    # If SecurityMiddleware not found for some reason, append at the front to still apply it.
    MIDDLEWARE.insert(0, "config.settings.csp_headers")

# 3) Proxy / SSL helper and admin redirect exemptions
#    Useful when running behind Render / other proxies and to avoid redirect loops.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Avoid redirect loop for admin login if you handle it differently at proxy level
SECURE_REDIRECT_EXEMPT = [r"^admin69/login/$"]